# tiene que tener un nombre
name: di hola

# tiene que tener un evento
# on -> dice si pasa esto haz esto
on:
  # cada vez que se haga un push
  push:
    # en la rama main
    branches:
      - main

# esto es lo que hara cada vez que se haga un push
# job -> es la action que se ejecutara
jobs:
  # este es el nombre del job
  hola:
    # runs-on -> dice en que sistema correra
    runs-on: ubuntu-22.04
    # steps -> dice que pasos va a ejecutar
    steps:
      # nombre del paso (es opcional)
      - name: Echo the message
        run: echo "hola"
      - name: dime la fecha
      # date esta diciendo la fecha
        run: date