name: paralelo

on:
  push:
    branches: [main]

jobs:
  primer-job:
    runs-on: ubuntu-24.04
    steps:
      - name: primer-job
        run: echo 1

  segundo-job:
    runs-on: ubuntu-24.04
    steps:
      - name: segundo-job
        run: echo 2

  tercer-job:
    needs: [primer-job, segundo-job]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

  cuarto-job:
    runs-on: ubuntu-24.04
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/upload-artifact@v7
        with:
          name: instalacion-bun
          path: carpeta
  
  quinto-job:
    needs: [cuarto-job]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: instalacion-bun
          path: src/carpeta
      - name: instalar dependencias
        run: bun i

  sexto-job:
    needs: [cuarto-job]
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: bun run vitest:run

  septimo-job:
    needs: [cuarto-job]
    runs-on: ubuntu-24.04
    steps:
      - name: build
        run: bun run dev